### ISSUE TITLE
Graph resizing must be responsive and not change the dimensions of the parent container.

### ISSUE THREAD

**Issue by brandongit2** [brandongit2/proton#22]
Currently, the graph tries to take up as much room as possible.

**Comment by mchlp** [comment]
@brandongit2 What do you mean by _changing the dimensions of the parent container_?

**Comment by mchlp** [comment]
**Problem:** Canvas element (offsetWidth and offsetHeight) gets bigger after the canvas is resized (height and width)

**Comment by mchlp** [comment]
Fixed with 0366ced8778a1065992fa1decec40462a1936f04
